### ISSUE TITLE
Installed modes are missing files


### ISSUE THREAD

**Issue by nlhowell** [apertium/apertium-uzb#9]
modes.xml includes some modes with `install="yes"`, but the required
files aren't installed.

Some generic suggestions:
* -lexc and -twol modes probably aren't useful to users
* -spell modes should depend on --enable-ospell
* .deps files are never installed, so any modes using them shouldn't be
  installed.

* Messages for package app-dicts/apertium-uzb-9999:

* Failed to find '/usr/share/apertium/apertium-uzb/.deps/uzb.twol.hfst' in install image.
* QA: missing files required for mode uzb-twol.
* Failed to find '/usr/share/apertium/apertium-uzb/.deps/uzb.lexc.hfst' in install image.
* QA: missing files required for mode uzb-lexc.

**Comment by ftyers** [comment]
Fixed in 411917d.
